### ISSUE TITLE
[question] Why create the temporary file?

### ISSUE THREAD

**Issue by codesections** [sagiegurari/run_script#11]
Thanks again for `run_script`.  I've spent a bit of time looking at the code in an effort to understand a bit more of what `run_script` is doing under the hood.  Most of the code makes perfect sense, but I'm a bit confused about the purpose of creating the temporary file.

The description in the README states
> While std::process::Command works great to execute standalone command, you need more manual code to take a script text and execute it.
>For this purpose, this library was created.

From this description, I expected that `run_script` would mostly be a wrapper around `std::process::Command`.  In some ways, it is exactly the wrapper I expected—but it also has this business with writing to a temporary file, immediately reading that temporary file back to a String, and then (eventually) deleting that file.  This *appears* at first to be wasted effort—which proves that I'm missing *something*.  What is the point of using the temporary file?

(Just to be clear, this issue is **not** to say that you have made the wrong decision in using a temp file.  I genuinely suspect I'm missing something fairly basic and would very much like to figure out what that is).

**Comment by sagiegurari** [comment]
it doesn't read the file actually.
command runs a single command. if you want multiple, you need to add the && character. what about functions? loops? so on.

so if you provide me a script, i modify it a bit (like adding the set x and e at the start for example), write it to a temp file and run it (not read) with a correct runner.
and naturally windows is just a bit different.
thats the manual code i was referring to in the readme.
ya, its not fun to write the file, but the script is written outside this lib and can be really complex and not single line.
i delete the file at the end for clean up

**Comment by codesections** [comment]
Thanks for the explanation – very helpful!

> so if you provide me a script, i modify it a bit (like adding the set x and e at the start for example), write it to a temp file and run it (not read) with a correct runner.

This makes me wonder: at least for linux, could you store the script as a string and then pass it as standard input to the script running (e.g., as if you had done `SCRIPT | sh`)?  All of `sh`/`bash`/`dash`/`fish`/`zsh` support taking a script via stdin.

I don't know if that would improve performance or not, but it would avoid any filesystem IO, which seems *likely* to speed things up.

Just a thought – and, again, thanks for the helpful library.

**Comment by sagiegurari** [comment]
not sure that would always work.
i would have to parse the thing and so on.... for example what if there are functions there?
basically I can't say we can take every script no matter what size and complexity and turn it into a one liner.

**Comment by codesections** [comment]
Makes sense – maybe one day I'll make the time to build an alternate library that uses stdin instead of a temp file and we can see how the performance compares :D  (But probably not).

I'm going to close this issue now; thanks again for the explanation.
