### ISSUE TITLE
Make it possible to specify the directory from which the script should execute

### ISSUE THREAD

**Issue by fbecart** [sagiegurari/run_script#13]
**Features Description**
When running a script, I would like to set the working directory where the script should execute.

**Describe the solution you'd like**
This most likely should be an additional field in `ScriptOptions`. This field should probably be a `PathBuf`.

**Code Sample**
```rust
let working_dir: PathBuf = ...;

let mut options = ScriptOptions::new();
options.dir = working_dir;

let child = run_script::spawn(..., &options);
...
```

**Comment by sagiegurari** [comment]
why not just add a "cd" command?

**Comment by fbecart** [comment]
@sagiegurari Yes, this works also.

I'm transitioning from `duct` to `run_script`, and there used to be such an option on duct: https://docs.rs/duct/0.11.1/duct/struct.Expression.html#method.dir
I figured this is a common enough use case that it could be offered as a feature. 
At least, this would allow me to avoid manipulating scripts as strings.

I would totally understand if you prefer to keep your API minimalist though.

Also, I'm curious about one thing. I see in the sources that we already `cd` in the current directory: https://github.com/sagiegurari/run_script/blob/4f35889f934f1e11f3b729e20f0dca281d8aab3a/src/runner.rs#L83
What's the purpose of this code?

**Comment by sagiegurari** [comment]
not familiar with duct.
so what run_script does, it create a script file in the temp dir location.
this means that it gets cleaned up either by run_script internally or by the OS as needed and you don't have leftovers.
but.... fact that the script is in the temp dir, i would like it to behave as if it was actually started in the cwd, so i added that cd.

so, for your use case, you are not dynamically building those scripts?
can you explain a bit more what is the flow?

**Comment by fbecart** [comment]
Thanks for the explanation about `cd`, this makes a lot of sense now.

I'm working on a build tool, for which the user will have to specify the scripts to run in order to build the projects in their repo.

Because projects can be located in different directories of the repo, I need to specify a directory where to execute each script.

Because they are entirely written by the user, my Rust code didn't have to manipulate any script so far.

**Comment by sagiegurari** [comment]
well... so run_script started from cargo-make which is a build tool i wrote that also supports having a different working directory per task.
however, the working directory impacts not just the script, but other things as well, so what i did in cargo-make is actually modify the cwd at the start of the task and revert at the end.

not sure if it makes sense for you or not.
if not, i can add the cwd param to the run script options, it should be pretty simple.

**Comment by fbecart** [comment]
It does make sense.

On my side, as you said, this is solved with a simple `cd`. I'm not blocked by this feature.

I'm happy if this feature lands, and I'm satisfied as well to use `run_script` with the current feature set.

Thanks a lot for extracting `run_script` from `cargo-make`. It will save me a lot of work.

**Comment by sagiegurari** [comment]
cool, so i can add that cwd to the options. will probably do it tomorrow.

**Comment by sagiegurari** [comment]
@fbecart I just pushed this feature into the 0.6.3 branch.
can you try to pull from there and give it a try?
if it works well, i'll release it to crates.io
i added to the options working_directory which takes a string that i just use to add another cd command.

**Comment by fbecart** [comment]
I tried it and it works as expected 👍

Instead of an `Option<String>`, could `working_directory` be an `Option<PathBuf>`?

**Comment by sagiegurari** [comment]
make sense. just did it and i'll be releasing it in few minutes.
thanks a lot for the idea.

**Comment by sagiegurari** [comment]
released. closing this issue
