### ISSUE TITLE
Ability to not show CMD popup when script is executed in windows.

### ISSUE THREAD

**Issue by ashutoshxhq** [sagiegurari/run_script#18]
### Feature Description
Currently when I do a release build, Every time I execute a script, a CMD window pops up in windows. Is there a way to not have that behavior and execute the command in detached mode. 

### Describe The Solution You'd Like
Possibly a flag in options that I can pass to toggle the behavior if I need the CMD window to pop up or not.

**Comment by sagiegurari** [comment]
@ashutoshxhq i missed this one, sorry.
anyhow, on windows run_script calls cmd, but in [script options](https://sagiegurari.github.io/run_script/api/run_script/types/struct.ScriptOptions.html) you can define a different runner. maybe that would resolve it?
i don't have a windows machine to test, but if you have a flag to cmd to prevent the window, i can add that.

**Comment by aria-aghaei** [comment]
Hi, according to [this stackoverflow](https://stackoverflow.com/questions/45549442/use-cmd-c-but-hide-the-console-window) you can minimize the cmd window by setting the runner to start.exe, setting a minimize flag and having it run cmd. If you want, I can implement and make a PR.

**Comment by sagiegurari** [comment]
cool. so the options do allow ro switch cmd with start.exe but not provide args line to the runner.
so maybe that should be the solution and than anyone can have full control of the invocation.
a PR would be great

**Comment by aria-aghaei** [comment]
I looked into it and "start" is an inbuilt process for cmd, there is no exe and no way to use it through rust std::process::command. However you still can run batch files including cmd commands in a hidden window by making powershell the runner and passing it "-window hidden". 

I just added my runner args implementation as a PR, take a look and let me know any comments, etc.

**Comment by sagiegurari** [comment]
this is now release. thanks @aria-aghaei for the PR.
