### ISSUE TITLE
Running make with run script causes /tmp error

### ISSUE THREAD

**Issue by LDprg** [sagiegurari/run_script#23]
### Describe The Bug
When running make I get an error about a missing /tmp/<random string> file. Its definitely not a make or rust command bug since manual and automatic (with rust commanfs) calls work perfectly fine.

### To Reproduce
Run make to build for example xz (after configure which works) with run script 

### Error Stack

```console
Will add later
```

### Code Sample

```rust
Will add later
```

**Comment by sagiegurari** [comment]
I really don't understand the issue. the explanation is not clear at all, no stack, no example. 
what is the expectation here?

**Comment by LDprg** [comment]
Sry I am currently unable to send code (will add them by the end of next week), because I cant access my laptop where the code is stored.

For clarification I am running a linux make command with run script which if invoked manually just works and compiles some external program (in my case the xz program on linux). However if runned by runscript the command fails and complains about a missing file in the /tmp/ directory. It seems like make just failes (not during Makefile run or anything just right at the start of the command).

So it seems that runscript does anything in its setup of the command that gnu make command fails. Other commands have been working fine.

@sagiegurari sorry for the bad issue quality.
