### ISSUE TITLE
Understanding output.

### ISSUE THREAD

**Issue by webbrandon** [sagiegurari/run_script#3]
#### Problem Description
I run a script using `cargo install` and even though it should provide output no output is provided by value response.  It does however complete the build and install commands given and printing text seems to be fine.

#### Code Example

```rust
pub fn run_build_script(script: &String) -> String {
    let mut options = ScriptOptions::new();
    options.runner = None; 
    options.capture_output = true; 
    options.exit_on_error = false; 
    options.print_commands = true;

    let args = vec![];

    let (code, output, error) = run_script::run(
        script,
        &args,
        &options,
    ).unwrap();
    if code == 0 {
        output
    } else {
        println!("{} : {}", code, error);
        bad_format_close_app();
    }
}
```

```bash
#!/bin/bash
echo "installing"
cargo build -verbose
cargo install --force

exit 0
```

**Comment by sagiegurari** [comment]
the second code snippet is the script trxt you provided?

**Comment by sagiegurari** [comment]
cargo build redirects its output to the error stream and not the standard output stream. so you need to print the variable 'error' and not 'output'.
why cargo directs to error stream? i have no idea.
