### ISSUE TITLE
Stream stdout and stderr

### ISSUE THREAD

**Issue by ericwooley** [sagiegurari/run_script#4]
**Features Description**
Instead of a string returned at the end of execution. It would be great to be able to get direct access to the stream.

**Describe the solution you'd like**
A new fn, or macro, which has almost the same api as the current one, except gives you access to stream processing. Something like the second answer here https://stackoverflow.com/questions/31992237/how-would-you-stream-output-from-a-process

**Code Sample**
```rust
// --snip--
        let stdout = cmd.stdout.as_mut().unwrap();
        let stdout_reader = BufReader::new(stdout);
        let stdout_lines = stdout_reader.lines();

        for line in stdout_lines {
            println!("Read: {:?}", line);
       }
```
**One final thing**
🚀 🚀 This project was exactly what i was looking for, and worked great. Thanks for making it!

**Comment by sagiegurari** [comment]
I'll check this out. thanks for the suggestion

**Comment by sagiegurari** [comment]
Not sure I'll have time in the near future to implement this feature. Happy to accept a PR if you wish.

**Comment by ericwooley** [comment]
ok, cool, thanks! I'll see if i can find some time this weekend.

**Comment by sagiegurari** [comment]
run_script::spawn gives you direct access to the child process. i'm pretty sure you can then use it for this purpose.
i'll be closing this one for now.
