### ISSUE TITLE
Running a script inthe background (like std::process::Command::spawn)

### ISSUE THREAD

**Issue by codesections** [sagiegurari/run_script#7]
Thanks so much for this great project!

Unless I'm missing something big, it looks like it's not currently possible to use `run_script` to run a script in the background.  (That is, all the `run_script` functions use `std::process::Command::output` to wait for the output instead of `std::process::Command::spawn`, which would run the process in a new shell in the background.)

If that's correct, would you be interested in adding that option?  I think it would be fairly straightforward to add a `spawn_command` function that mirrors the `run_command` function (and corresponding macros for ergonomics).

Alternatively, am I missing something basic?

**Comment by sagiegurari** [comment]
I think this was requested before :)
I'll try to get to it start of next week.

**Comment by sagiegurari** [comment]
@codesections this is now implemented in 0.4.0 version which has now been released.
you have new spawn function that takes same args as run but returns the Child process handle.
and you have spawn_script! macro which is the same as the run_script! macro and also returns child process.

Hope it resolves your issue and if not, open a new issue or reopen this one.
thanks for the suggestion

**Comment by codesections** [comment]
Thanks for this—very much appreciated!
